//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FidelityPension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FidelityPension.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us today.
        /// </summary>
        public static string CTA_SubTitle {
            get {
                return ResourceManager.GetString("CTA_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Questions About Micro Pension?.
        /// </summary>
        public static string CTA_Title {
            get {
                return ResourceManager.GetString("CTA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Fidelity Pension Managers Limited (Fidelity Pension), we recognise that good administration, which devolves to efficient and effective processes, systems and controls; and, prompt and qualitative services, are the bedrock of a well-run pension scheme..
        /// </summary>
        public static string Footer_About_Writeup {
            get {
                return ResourceManager.GetString("Footer_About_Writeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information contact us.
        /// </summary>
        public static string For_More_Information_Contact_Us {
            get {
                return ResourceManager.GetString("For_More_Information_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Our Board Of Directors.
        /// </summary>
        public static string Meet_Our_Board_Of_Directors {
            get {
                return ResourceManager.GetString("Meet_Our_Board_Of_Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        public static string Our_Address {
            get {
                return ResourceManager.GetString("Our_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Company.
        /// </summary>
        public static string Our_Company {
            get {
                return ResourceManager.GetString("Our_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T - Trust, R - Respect, A - Ambition, I - Innovation, T - Teamwork, S - Speed/Safty .
        /// </summary>
        public static string Our_Core_Value {
            get {
                return ResourceManager.GetString("Our_Core_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Core Values.
        /// </summary>
        public static string Our_Core_Value_Title {
            get {
                return ResourceManager.GetString("Our_Core_Value_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Gallery.
        /// </summary>
        public static string Our_Gallery {
            get {
                return ResourceManager.GetString("Our_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide safe and rewarding pension services for a happy retirement..
        /// </summary>
        public static string Our_Mission {
            get {
                return ResourceManager.GetString("Our_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION.
        /// </summary>
        public static string Our_Mission_Title {
            get {
                return ResourceManager.GetString("Our_Mission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &amp; Services.
        /// </summary>
        public static string Our_Products_and_Services {
            get {
                return ResourceManager.GetString("Our_Products_and_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be a leading and most innovative PFA, managing pension assets transparently and profitably..
        /// </summary>
        public static string Our_Vision {
            get {
                return ResourceManager.GetString("Our_Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISION.
        /// </summary>
        public static string Our_Vision_Title {
            get {
                return ResourceManager.GetString("Our_Vision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An RSA holder whose employment has been terminated or who has been disengaged and has not been in any.
        /// </summary>
        public static string PS_Benefit_Administration_SubTitle {
            get {
                return ResourceManager.GetString("PS_Benefit_Administration_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Administration.
        /// </summary>
        public static string PS_Benefit_Administration_Title {
            get {
                return ResourceManager.GetString("PS_Benefit_Administration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product enables expatriate employees in companies registered in Nigeria and Nigerian citizens working.
        /// </summary>
        public static string PS_Cross_Border_Pension_SubTitle {
            get {
                return ResourceManager.GetString("PS_Cross_Border_Pension_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross border Pension.
        /// </summary>
        public static string PS_Cross_Border_Pension_Title {
            get {
                return ResourceManager.GetString("PS_Cross_Border_Pension_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a financial arrangement for pension services for self-employed persons and persons working in organizations.
        /// </summary>
        public static string PS_Micro_Pension_SubTitle {
            get {
                return ResourceManager.GetString("PS_Micro_Pension_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Pension.
        /// </summary>
        public static string PS_Micro_Pension_Title {
            get {
                return ResourceManager.GetString("PS_Micro_Pension_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you’ve got a general question or a specific query relating to your pension, our in-house experts.
        /// </summary>
        public static string PS_Retirement_Advisory_SubTitle {
            get {
                return ResourceManager.GetString("PS_Retirement_Advisory_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement Advisory.
        /// </summary>
        public static string PS_Retirement_Advisory_Title {
            get {
                return ResourceManager.GetString("PS_Retirement_Advisory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every employee or contributor under the new pension scheme is expected to open RSA in his/her.
        /// </summary>
        public static string PS_RSA_Short_Note {
            get {
                return ResourceManager.GetString("PS_RSA_Short_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement Saving Account.
        /// </summary>
        public static string PS_Title_RSA {
            get {
                return ResourceManager.GetString("PS_Title_RSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voluntary Contribution.
        /// </summary>
        public static string PS_Title_Voluntary_Contribution {
            get {
                return ResourceManager.GetString("PS_Title_Voluntary_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer to additional contributions you can decide to include to your mandatory pension.
        /// </summary>
        public static string PS_Voluntary_Contribution_Short_Note {
            get {
                return ResourceManager.GetString("PS_Voluntary_Contribution_Short_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Slider1_SubTitle {
            get {
                return ResourceManager.GetString("Slider1_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Micro Pension plan.
        /// </summary>
        public static string Slider1_Title {
            get {
                return ResourceManager.GetString("Slider1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Retirement Savings Account Today !.
        /// </summary>
        public static string Slider2_SubTitle {
            get {
                return ResourceManager.GetString("Slider2_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan to Retire Happily.
        /// </summary>
        public static string Slider2_Title {
            get {
                return ResourceManager.GetString("Slider2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Retirement Savings Account Today !.
        /// </summary>
        public static string Slider3_SubTitle {
            get {
                return ResourceManager.GetString("Slider3_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build While You Can.
        /// </summary>
        public static string Slider3_Title {
            get {
                return ResourceManager.GetString("Slider3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow and always with a retirement Savings Account with Fidelity Pension Managers..
        /// </summary>
        public static string Slider4_SubTitle {
            get {
                return ResourceManager.GetString("Slider4_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the music playing today,.
        /// </summary>
        public static string Slider4_Title {
            get {
                return ResourceManager.GetString("Slider4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view more.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voluntary Contribution
        ///
        ///Voluntary Contributions (VC) refers to additional contributions you can decide to include to your mandatory pension contributions for the purpose of augmenting them or simply to set aside as savings towards a goal. VC is an optional contribution made above the mandatory 18% employer and employee contributions into an individual’s Retirement Savings Account (RSA). You could access your VC subject to the extant rules on withdrawal released by PenCom. 
        ///
        ///Consequently, the Management  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Voluntary_Contribution_Page {
            get {
                return ResourceManager.GetString("Voluntary_Contribution_Page", resourceCulture);
            }
        }
    }
}
