// <auto-generated />
namespace FidelityPension.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class D6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(D6));
        
        string IMigrationMetadata.Id
        {
            get { return "201907101814368_D6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
